#!/usr/bin/env python

import subprocess
import re
import datetime

from subprocess import Popen

now = datetime.datetime.now()

dir_to_backup = "/home/ben/code/persistant-backup/docs"
backup_dir = "/home/ben/code/persistant-backup/backup/{}-{}-{}-{}-{}-{}".format(now.year, now.month, now.day, now.hour, now.minute, now.second)
ip = "192.168.5.123"


def is_host_up(ip):
    ping_response = Popen(["/bin/ping", "-c1", "-w1", "-q", ip], stdout=subprocess.PIPE).stdout.read()
    return re.search(b"100% packet loss", ping_response) is None

def backup_host():
    response = Popen(["/bin/rsync", "-a", dir_to_backup, backup_dir], stdout=subprocess.PIPE).stdout.read()

backup_host()
